### ISSUE TITLE
It seems not to work.

### ISSUE THREAD

**Issue by RobertoMalatesta** [LukasHechenberger/atom-json-editor#1]
Hi,
Tried on this file, the toggle menu is not showing the form.

Atom: latest
Platform: Kubuntu 14.04 LTS.

Thank for your time,

R

======================== FILE BELOW ==========================

{
    "title": "Person",
    "type": "object",
    "id": "person",
    "properties": {
        "name": {
            "type": "string",
            "description": "First and Last name",
            "minLength": 4
        },
        "age": {
            "type": "integer",
            "default": 21,
            "minimum": 18,
            "maximum": 99
        },
        "gender": {
            "type": "string",
            "enum": [
                "male",
                "female"
            ]
        }
    }
}

**Comment by LukasHechenberger** [comment]
I’m sorry, atom-json-editor does not work from the menubar, I will remove the entry.
Please read Readme.md https://atom.io/packages/atom-json-editor for proper use.

Greets, Lukas

**Comment by RobertoMalatesta** [comment]
Ok Lukas,

Thank for your time,

R.
